output_topics:  [/sh_thj1_mixed_position_velocity_controller/command,  
                 /sh_thj2_mixed_position_velocity_controller/command,  
                 /sh_thj3_mixed_position_velocity_controller/command, 
                 /sh_thj4_mixed_position_velocity_controller/command, 
                 /sh_thj5_mixed_position_velocity_controller/command,  
                 /sh_ffj0_mixed_position_velocity_controller/command,
                 /sh_ffj3_mixed_position_velocity_controller/command,  
                 /sh_ffj4_mixed_position_velocity_controller/command,  
                 /sh_mfj0_mixed_position_velocity_controller/command,  
                 /sh_mfj3_mixed_position_velocity_controller/command,  
                 /sh_mfj4_mixed_position_velocity_controller/command, 
                 /sh_rfj0_mixed_position_velocity_controller/command, 
                 /sh_rfj3_mixed_position_velocity_controller/command,  
                 /sh_rfj4_mixed_position_velocity_controller/command,
                 /sh_lfj0_mixed_position_velocity_controller/command,  
                 /sh_lfj3_mixed_position_velocity_controller/command,  
                 /sh_lfj4_mixed_position_velocity_controller/command, 
                 /sh_lfj5_mixed_position_velocity_controller/command, 
                 /sh_wrj1_mixed_position_velocity_controller/command,  
                 /sh_wrj2_mixed_position_velocity_controller/command]

#JOINT ORDER:
# THJ1
# THJ2
# THJ3
# THJ4
# THJ5
# FFJ0
# FFJ3
# FFJ4
# MFJ0
# MFJ3
# MFJ4
# RFJ0
# RFJ3
# RFJ4
# LFJ0
# LFJ3
# LFJ4
# LFJ5
# WRJ1
# WRJ2
