output_topics:  [/impedance_joint_controller/THJ1/command,
                 /impedance_joint_controller/THJ2/command, 
                 /impedance_joint_controller/THJ3/command,  
                 /impedance_joint_controller/THJ4/command,
                 /impedance_joint_controller/THJ5/command, 
                 /impedance_joint_controller/FFJ0/command,
                 /impedance_joint_controller/FFJ3/command,
                 /impedance_joint_controller/FFJ4/command, 
                 /impedance_joint_controller/MFJ0/command,
                 /impedance_joint_controller/MFJ3/command,
                 /impedance_joint_controller/MFJ4/command,
                 /impedance_joint_controller/RFJ0/command, 
                 /impedance_joint_controller/RFJ3/command,
                 /impedance_joint_controller/RFJ4/command,
                 /sh_lfj0_mixed_position_velocity_controller/command,  
                 /sh_lfj3_mixed_position_velocity_controller/command,  
                 /sh_lfj4_mixed_position_velocity_controller/command, 
                 /sh_lfj5_mixed_position_velocity_controller/command, 
                 /sh_wrj1_mixed_position_velocity_controller/command,  
                 /sh_wrj2_mixed_position_velocity_controller/command]

#JOINT ORDER:
# THJ1
# THJ2
# THJ3
# THJ4
# THJ5
# FFJ0
# FFJ3
# FFJ4
# MFJ0
# MFJ3
# MFJ4
# RFJ0
# RFJ3
# RFJ4
# LFJ0
# LFJ3
# LFJ4
# LFJ5
# WRJ1
# WRJ2
